#!/usr/bin/env bash


# only install glide if it is not installed
type glide >/dev/null 2>&1 || (echo "installing Glide" && curl https://glide.sh/get | sh )

export GOPATH="$(pwd)/src/datadog-firehose-nozzle/:$GOPATH"

pushd src/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle
  glide install
popd

rm -rf src/datadog-firehose-nozzle/pkg
