meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: dd-agent_z1
    templates:
    - name: dd-agent
      release: dd-agent
    instances: 1
    resource_pool: small_z1
    persistent_disk: 0

properties:
  dd:
    api_key: datadog
    tags:
    - test1
    - test2

